---
title: Biodegradable alternatives to plastic mesh bags conventionally used in freshwater
  macroinvertebrate analysis within the Bronx River, NYC
author: "R.E. Segui-Baez, G.A. Rueda Moreno, R. Ward, K. Schneider Paolantonio"
date: "`r Sys.Date()`"
output: word_document
bibliography: references.bib
---

```{r pre-requisite scripts, echo=FALSE}
#source data processor scripts----
source("Rscripts/biodiversity.R")#script to process biodiversity data
source("Rscripts/water_quality.R")#script to process water quality data
source("Rscripts/stats.R") #script to analyze previously loaded data

```

```{r setup, include=FALSE}
#knitr options----
knitr::opts_chunk$set(echo = TRUE)
#dependencies----
require(tidyverse)
require(GGally)
require(vegan)
require(ggpubr)
require(tidyverse)
require(viridisLite)
require(rlang)
require(car)
require(corrplot)
require(factoextra)

#plotting source code----
#set plotting theme function 
theme_rafa <- function(base_size = 12){
  theme_pubr(base_family="sans") %+replace%
    theme(panel.background  = element_blank(),
          plot.background = element_rect(fill="transparent", colour=NA), 
          legend.background = element_rect(fill="transparent", colour=NA),
          legend.key = element_rect(fill="transparent", colour=NA),
          legend.text = element_text(size=base_size * 0.7),
          legend.title = element_text(size = base_size * 0.8, 
                                      face = "bold"),
          axis.text = element_text(size = base_size*0.85),
          axis.title = element_text(size = base_size * 1.2),
          plot.title.position = "panel",
          plot.caption.position = "panel",
          plot.title = element_text(
            size = base_size * 1.25,
            face = "bold", 
            hjust = 0.5,
            vjust = 1),
          plot.subtitle = element_text(
            size = base_size * 0.9,
            vjust = 1),
          plot.caption =  element_text(
            size = base_size*0.75,
            hjust = 0.5)
    )
}

#bag type barplot function:
#PARAMS: 
  #index(string): a string specifying the desired index
bt_barplot <- function(index){
  #tukey tibble
  groupings_tibble <- diversity_tukeys[[index]]$groups %>%
rownames_to_column("material")
  #calculate mean and standard error of chosen index
  new_tbl <- LPP_FullData%>%
  filter(is.na(material) == FALSE)%>% #remove na values from material before calculations
    group_by(material) %>% #group by material
    mutate(index_se = sd(get(index), na.rm = T)/sqrt(n())) %>% # calc SE
    summarise(index = mean(get(index), na.rm = T), index_se = mean(index_se)) #summarise into mean
  #merge two tibbles
  new_tbl <- inner_join(new_tbl, groupings_tibble, by ="material")
  
  #plotting
  ggplot(new_tbl, aes(x = reorder(material, -index, sum), y = index)) +
    geom_col(aes(fill = reorder(material, -index, sum))) +
    geom_errorbar(aes(ymin = index - 2*index_se, ymax = index + 2*index_se)) +
geom_text(aes(y = (index + 3*index_se), label =groups)) +
    
    theme_bw() +
    scale_fill_viridis_d()+
    theme_rafa(base_size = 15) +
    theme(axis.text.x = element_text(angle = -15, vjust = 0.5))+
    labs(x = "material", title = "Diversity Index by Bag material", y = paste(index),
         fill = "material")
}

#water quality time series plots by site
#PARAMS:
  #param(string): a string specifying the water quality parameter

wq_ts_BySite <- function(param){
  #create symbol of parameter name and se for tidy eval in ggplot2 call
  param<- sym(param)
  param_se <- sym(paste(param,"se", sep = "_"))
  ggplot(wq_list$raw_water_quality, aes(x = date, y = !!param, color = site)) +
    #geom layers
    geom_point() +
     geom_smooth(method = 'lm')+
    #labels
    labs(title = paste(param, "Seasonality"), x = "Date")+
    #theme adjustments
    theme_bw() +
    theme_rafa(base_size = 15) +
    scale_color_viridis_d(begin = 0.1, end = 0.9)
}
```

### Tables

```{r wq table}
readxl::read_xlsx("Rfigs/summaryFigures.xlsx", sheet = 2) %>%
knitr::kable(caption = "Table 2: Water quality parameters averaged over the course of the sampling period")
```

### Plots

```{r wq plots, eval=FALSE}
#water quality dot plots----
#water quality by date on the y and site as color
wq_ts_BySite("P") +labs( title = "Phosphorous Seasonality",y = "Phosphorous (mg/L)")
wq_ts_BySite("pH")
wq_ts_BySite("NH3") +labs(y = "Ammonia (mg/L)")
wq_ts_BySite("DO") + labs(title = "Dissolved Oxygen Seasonality",
                          y = "% DO")
wq_ts_BySite("Temp") + labs(title = "Temperature Seasonality",
                            y = "Temp (°C)")
wq_ts_BySite("Cond") + labs(title = "Conductivity Seasonality", y = "Conductivity (mS)")
wq_ts_BySite("Nitrogen") + labs(y = "Nitrogen (mg/L)")
wq_ts_BySite("Flow") + labs(title = "Flow rate Seasonality",
                            x = "Date", y = "Flow (m/s)")

#biodiversity plots----
bt_barplot( "richness")+ labs(x = "Material", y="Richness")  
bt_barplot( "shannon")+ labs(x = "Material", y= "Shannon Diversity")
bt_barplot( "simpson")+ labs(x = "Material",y= "Simpson Diversity")
bt_barplot( "invsimp")+ labs(x = "Material",y= "Inverse-Simpson Diversity")
bt_barplot("even")+ labs(x = "Material",y= "Shannon Evenness")

#Bray Curtis Dissimil plots----
#by site
ggplot(BC_BySite_tibble, aes(x = site_comp, y = bc_score, fill = site_comp)) +geom_col() +
  theme_rafa() + coord_cartesian(ylim = c(0, 1)) + scale_fill_viridis_d() +
  labs(title = "Community Dissimilarity between sites",
       x = "Site Comparisons", y =" Bray Curtis Dissimilarity", fill = "Comparisons")

#by material (plastic comparisons only)
ggplot(BC_ByMat_tibble[7:10,], aes(x = mat_comp, y = bc_score, fill = mat_comp)) +geom_col() +
  theme_rafa() + scale_fill_viridis_d()+
  coord_cartesian(ylim = c(0, 1)) +
  labs(title = "Community Dissimilarity between plastic and biodegradable bags", x = "Material Comparison",
       y = "Bray Curtis Dissimilarity", fill = "Comparisons")

#NMDS plots----
#extract scores from NMDS object
TC_NMDS_Scores <- as_tibble(scores(taxaCount_NMDS, display = "sites"))
TC_NMDS_Scores$site <- LPP_FullData$site
TC_NMDS_Scores$date <- LPP_FullData$date
TC_NMDS_Scores$material <- LPP_FullData$material

#plotting
ggplot(TC_NMDS_Scores, aes(x = NMDS1, y = NMDS2, fill = material)) +
  geom_hline(yintercept = 0, linetype = 5) + geom_vline(xintercept = 0, linetype = 5) +
  geom_point(shape = 21, size = 2.5) +
  facet_wrap(~date)+
  theme_rafa() +
  labs(title = "Non-Metric Dimensional Scaling of Community Matrices")+
  scale_fill_viridis_d()
```




